Fix compiler warning in GCC v11 about small_cpy()
Full warning text (converted into error in Release mode):

In function 'small_cpy',
    inlined from 'buffered_accumulation' at
    \LibAscon\src\ascon_buffering.c:150:9:
LibAscon\src\ascon_buffering.c:27:18: error: writing 1 byte into a
    region of size 0 [-Werror=stringop-overflow=]
    27 |         *(dst++) = *(src++);
       |         ~~~~~~~~~^~~~~~~~~~

The reason for the error is unclear. Replacing the while-loop with
a for-loop does not trigger it anymore, so this was picked as a
solution.